import { createCofheConfig, createCofheClient } from '@cofhe/sdk/web';
import { chains } from '@cofhe/sdk/chains';
import type { EncryptedItemInput, Encryptable } from '@cofhe/sdk';
import { useEffect, useRef, useState } from 'react';
import { usePublicClient, useWalletClient } from 'wagmi';
import { CHAIN_ID } from '@/lib/contracts';

// Module-level singletons — created once, shared across all hooks.
const _config = createCofheConfig({ supportedChains: [chains.arbSepolia] });
export const cofheClient = createCofheClient(_config);

let _cofheReady = false;
export function isCofheReady() { return _cofheReady; }
let _lastPublicClient: any | null = null;
let _lastWalletClient: any | null = null;

// Normalise a signature string to a viem-compatible 0x-prefixed hex.
export function toHexSig(sig: string): `0x${string}` {
  return (sig.startsWith('0x') ? sig : `0x${sig}`) as `0x${string}`;
}

// Ensure an EncryptedItemInput's signature field is 0x-prefixed for viem tuple encoding.
export function normaliseEnc(enc: EncryptedItemInput) {
  return {
    ctHash:       enc.ctHash,
    securityZone: enc.securityZone,
    utype:        enc.utype as number,
    signature:    toHexSig(enc.signature),
  };
}

/**
 * Encrypt inputs for the active chain (Arbitrum Sepolia) with an explicit chainId.
 * This avoids verifier-side mismatches when the SDK can't infer chainId reliably in-browser.
 */
export async function encryptInputsOnChain(inputs: Encryptable[]) {
  return await cofheClient
    .encryptInputs(inputs)
    .setChainId(CHAIN_ID)
    .execute();
}

export async function getSelfPermitSafe() {
  const hasSealingPair = (permit: any): boolean =>
    !!permit?.sealingPair?.privateKey && !!permit?.sealingPair?.publicKey;
  const clearCorruptedPermitState = async () => {
    try {
      const all = await cofheClient.permits.getPermits();
      for (const [hash, permit] of Object.entries(all ?? {})) {
        if (!hasSealingPair(permit)) {
          await cofheClient.permits.removePermit(hash);
        }
      }
      await cofheClient.permits.removeActivePermit();
    } catch {
      // best effort cleanup
    }
  };

  const tryGet = async () => {
    // Prefer an existing valid active permit to avoid regenerating key material.
    const active = await cofheClient.permits.getActivePermit();
    if (active && hasSealingPair(active)) return active;
    if (active && !hasSealingPair(active)) {
      await cofheClient.permits.removeActivePermit();
    }

    // Recover from corrupted active pointer by selecting any valid stored self permit.
    const all = await cofheClient.permits.getPermits();
    for (const [hash, permit] of Object.entries(all ?? {})) {
      if ((permit as any)?.type === 'self' && hasSealingPair(permit)) {
        cofheClient.permits.selectActivePermit(hash);
        return permit;
      }
    }

    // Create a new self permit when no valid stored one exists.
    const issuer = cofheClient.account;
    if (issuer) {
      return cofheClient.permits.createSelf({
        issuer,
        name: 'Autogenerated Self Permit',
      });
    }
    return cofheClient.permits.getOrCreateSelfPermit();
  };
  try {
    return await tryGet();
  } catch (err: any) {
    const msg = String(err?.message ?? err ?? '');
    const shouldReconnect = msg.includes('keyPair') || msg.includes('Cannot read properties of undefined');
    if (!shouldReconnect || !_lastPublicClient || !_lastWalletClient) throw err;

    await clearCorruptedPermitState();
    // Recover from stale in-memory SDK state.
    cofheClient.disconnect();
    _cofheReady = false;
    await cofheClient.connect(_lastPublicClient, _lastWalletClient);
    _cofheReady = true;
    return await tryGet();
  }
}

export async function decryptForTxWithRetry(
  ctHash: bigint,
  options?: { label?: string; retries?: number; delayMs?: number; tryWithoutPermitFallback?: boolean }
): Promise<{ decryptedValue: bigint; signature: string }> {
  const label = options?.label ?? 'decryptForTx';
  const retries = options?.retries ?? 12;
  const delayMs = options?.delayMs ?? 5000;
  const tryWithoutPermitFallback = options?.tryWithoutPermitFallback ?? false;
  let lastErr: unknown;

  const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

  for (let attempt = 1; attempt <= retries; attempt++) {
    try {
      const permit = await getSelfPermitSafe();
      const res = await cofheClient.decryptForTx(ctHash).withPermit(permit).execute();
      return { decryptedValue: res.decryptedValue as bigint, signature: res.signature as string };
    } catch (err: any) {
      lastErr = err;
      const msg = String(err?.message ?? err ?? '');
      const keyPairOrPermitIssue =
        msg.includes('keyPair') || msg.includes('Cannot read properties of undefined') || msg.includes('permit');

      if (tryWithoutPermitFallback && keyPairOrPermitIssue) {
        try {
          const res = await cofheClient.decryptForTx(ctHash).withoutPermit().execute();
          return { decryptedValue: res.decryptedValue as bigint, signature: res.signature as string };
        } catch (fallbackErr) {
          lastErr = fallbackErr;
        }
      }

      if (attempt < retries) {
        // eslint-disable-next-line no-console
        console.warn(`[CoFHE] ${label} attempt ${attempt}/${retries} failed, retrying...`, msg);
        await sleep(delayMs);
      }
    }
  }

  throw new Error(`${label} failed after ${retries} attempts: ${String(lastErr)}`);
}

/**
 * Connects the module-level cofheClient to the current wagmi public/wallet clients.
 * Must be called high up in the component tree (e.g. inside TradePage or App).
 * Returns `ready = true` once connected.
 */
export function useCofheClient() {
  const publicClient              = usePublicClient();
  const { data: walletClient }    = useWalletClient();
  const [ready, setReady]         = useState(false);
  const connectingRef             = useRef(false);

  useEffect(() => {
    if (!publicClient || !walletClient || connectingRef.current) return;
    connectingRef.current = true;
    _lastPublicClient = publicClient;
    _lastWalletClient = walletClient;
    cofheClient
      .connect(publicClient as any, walletClient as any)
      .then(() => { _cofheReady = true; setReady(true); })
      .catch((err: unknown) => console.error('[CoFHE] connect failed:', err))
      .finally(() => { connectingRef.current = false; });
  }, [publicClient, walletClient]);

  return { cofheClient, ready };
}
